BLOCK_WIDTH = 75
CHARACTER_WIDTH = 50
INSTRUCTION_WIDTH = 50

# Main Menu
MENU_TITLE_SIZE = 45
MENU_CREDITS_SIZE = 15
MENU_CREDITS_PADDING = 6
MENU_SELECTION_SIZE = 22
MENU_SELECTION_SPACING = 10
MENU_TITLE_COLOR = '#FC7753'
MENU_CREDITS_COLOR = '#FC7753'
SELECTED_SELECTION_COLOR = '#FC7753'
UNSELECTED_SELECTION_COLOR = '#A14127'
MENU_ENTER_COLOR = '#FC7753'


BACKGROUND_COLOR = '#F2EFEA'
BORDER_COLOR = '#E6E6E6'
WALL_COLOR = '#FC7753'
TEXT_COLOR = '#403D58'
CHARACTER_COLOR = '#66D7D1'
PATH_COLOR = '#DBD56E'
IMAGES_PATH = '../assets/images/'
ROBOT_IMG = 'aibo.png'